#!/usr/bin/env bash

PORT=5554

start() {
     echo "Starting emulator using port $PORT..."
     emulator64-arm -avd emul-android-4.2 -gpu on -no-skin -no-audio -no-window -port $PORT &
     wait
}

wait() {
     echo "Waiting for emulator to start..."

     boot_completed=`adb -e shell getprop sys.boot_completed 2>&1`
     timeout=0
     until [ "X${boot_completed:0:1}" = "X1" ]; do
          sleep 10
          boot_completed=`adb -e shell getprop sys.boot_completed 2>&1`
	      echo "Read boot_completed property: <$boot_completed>"
          let "timeout += 1"
          if [ $timeout -gt 60 ]; then
               echo "Failed to start emulator"
               exit 1
          fi
     done
}

case "$1" in
start)
     echo "Start Android Emulator"
     start
     ;;
wait)
     echo  "Wait for Android Emulator"
     wait
     ;;
stop)
     echo  "Stopping Android Emulator"
     kill `pidof emulator64-arm`
     ;;
*)
     echo "Usage $0 start|wait"
     ;;
esac
