#!/usr/bin/env bash

PORT=5554

start_window() {
     echo "Starting emulator using port $PORT..."
	 export LD_LIBRARY_PATH=$ANDROID_HOME/tools/lib:$LD_LIBRARY_PATH
     xvfb-run -s "+extension GLX" emulator64-arm -avd emul-android-4.2 -gpu on -no-skin -no-audio -port $PORT -qemu -m 768 &
     wait
}

start_no_window() {
     echo "Starting emulator using port $PORT..."
	 export LD_LIBRARY_PATH=$ANDROID_HOME/tools/lib:$LD_LIBRARY_PATH
     emulator64-arm -avd emul-android-4.2 -gpu on -no-skin -no-audio -no-window -port $PORT -qemu -m 768 &
     wait
}

wait() {
     echo "Waiting for emulator to start..."

     boot_completed=`adb -e shell getprop sys.boot_completed 2>&1`
     timeout=0
     until [ "X${boot_completed:0:1}" = "X1" ]; do
          sleep 10
          boot_completed=`adb shell getprop sys.boot_completed 2>&1 | head -n 1`
	      echo "Read boot_completed property: <$boot_completed>"
          let "timeout += 1"
          if [ $timeout -gt 1000 ]; then
               echo "Failed to start emulator"
               exit 1
          fi
     done
     adb shell input keyevent 82
}

case "$1" in
start-window)
     echo "Start Android Emulator in Window mode"
     start_window
     ;;
start-no-window)
     echo "Start Android Emulator in No-Window mode"
     start_no_window
     ;;
start)
     start_no_window
     ;;
wait)
     echo  "Wait for Android Emulator"
     wait
     ;;
stop)
     echo  "Stopping Android Emulator"
     adb emu kill
     ;;
poweroff)
     echo  "Powering off Android Emulator"
     adb shell reboot -p
     ;;
*)
     echo "Usage $0 start|wait"
     ;;
esac
